export const RESET_DATA = 'RESET_DATA';
export const SET_DATA = 'SET_DATA';
export const FETCH_DATA_FAILED = 'FETCH_DATA_FAILED';
export const UPDATE_SELECTED_IMAGE = 'UPDATE_SELECTED_IMAGE';
export const UPDATE_SELECTED_PAGE = 'UPDATE_SELECTED_PAGE';